# Generated by Django 5.2.8 on 2026-02-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_patient_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcareuser',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
