# Generated by Django 5.2.8 on 2026-02-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bed_data', '0009_beddatamodel_is_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotdatamodel',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
