# Generated by Django 5.2.8 on 2026-02-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bed_data', '0010_slotdatamodel_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotdatamodel',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
